# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to Netlify on commits to staging

on:
  push:
    branches: [ ci-cd ]
  pull_request:
    branches: [ staging ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x]

    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

    steps:
      # Checkout repo
      - uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run the tests and generate coverage report
        run: npm test -- --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

      - name: Build
        run: npm run build

      # Deploy the site with netlify-cli
      # - name: Deploy Site
      #   env:
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #   run: netlify deploy --dir=public --prod

      - name: actions successful
        id: successfulMsg
        uses: slackapi/slack-github-action@v1.18.0
        with:
          channel-id: ${{ secrets.CHANNEL_ID }}
          payload: |
            {
                "blocks": [
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": "GitHub Action build result: *${{ job.status }}*"
                        }
                    }
                ],
                "attachments": [
                    {
                        "title": "${{ github.event.pull_request.title || github.event.head_commit.message }}",
                        "text": "${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
                        "color": "#7CD197"
                    }
                ]
            }
        if: success()

      - name: action failed
        id: failureSlackNotification
        uses: slackapi/slack-github-action@v1.18.0
        with:
          channel-id: ${{ secrets.CHANNEL_ID }}
          payload: |
            {
                "blocks": [
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": "GitHub Action build result: *${{ job.status }}*"
                        }
                    }
                ],
                "attachments": [
                    {
                        "title": "${{ github.event.pull_request.title || github.event.head_commit.message }}",
                        "text": "${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
                        "color": "#d91e1e"
                    }
                ]
            }
        if: failure()
